const maintenances = [
  {
    title: {
      english: "Burglared Maintenances",
      español: "Mantenimiento de Robos",
    },
    encoding: [
      {
        reason: "With signals, No Damage",
        type: "500",
        subtype: "501",
        text: "ROBO CON SEÑALES Y SIN DAÑOS. NO ES NECESARIO VIEW, POR FAVOR, DESCARGAR CÓDIGOS (especificar zona) DEL FOTODETECTOR (indicar nº de zona) Y SI NO LLEGAN IMAGENES RETIRAR FOTODETECTOR (especificar zona) Y ENVIAR A LA CENTRAL PARA EXTRAER IMAGENES. GRACIAS",
      },
      {
        reason: "With signals, With Damage",
        type: "500",
        subtype: "502",
        text: "ROBO CON SEÑALES Y CON DAÑOS. NO SE ACCEDE PARA REALIZAR VIEW. POR FAVOR, HACER VIEW O TRAER CENTRAL PARA HACERLO, RETIRAR FOTODETECTOR/ES:   PARA EXTRAER IMAGENES. NO COBRAR NADA A CLIENTE POR EL MATERIAL REPUESTO DEJANDO REFLEJADO EN PARTE LO SIGUIENTE: FIDELZACION: IMPORTE SUSTITUCIÓN POR ELEMENTO DAÑADO ASUMIDO POR SECURITAS DIRECT. GRACIAS",
      },
      {
        reason: "No signals, No Damage",
        type: "500",
        subtype: "503",
        text: 'ROBO SIN SEÑALES Y SIN DAÑOS. "REALIZAR VIEW EN LA INSTALACION" (en caso de no ser posible), EN CASO DE VER CAPTACIONES DE ALGÚN FOTODETECTOR RETIRARLO PARA EXTRAER IMAGENES / (si se puede hacer view) ESPECIFICAR LOS FOTODETECTORES QUE HAYAN CAPTADO PARA RETIRAR Y EXTRAER IMAGENES. REVISAR SISTEMA. GRACIAS',
      },
      {
        reason: "No signals, No Damage",
        type: "500",
        subtype: "504",
        text: "ROBO SIN SEÑALES Y CON DAÑOS. NO SE ACCEDE PARA REALIZAR VIEW. POR FAVOR, HACER VIEW O TRAER CENTRAL PARA HACERLO. RETIRAR FOTODETECTORES POR LOS QUE SE HAYAN PASADO PARA INTENTAR EXTRAER IMAGENES (especificar sensores) Y REPONER SISTEMA. NO COBRAR NADA A CLIENTE POR EL MATERIAL REPUESTO DEJANDO REFLEJADO EN PARTE LO SIGUIENTE: FIDELZACION: IMPORTE SUSTITUCIÓN POR ELEMENTO DAÑADO ASUMIDO POR SECURITAS DIRECT. GRACIAS",
      },
    ],
  },
];

export { maintenances };
